version: '3.8'
services:
  db:
    image: mysql:8.4.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-springboot2essentials
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
  devdojo_data:
